### ISSUE TITLE
Cannot run tests: update the xo dependency to the latest (currently v0.54.2)

### ISSUE THREAD

**Issue by leomav** [sindresorhus/camelcase#108]
Trying to run the tests it failed every time with the following error

> ➜  camelcase git:(main) ✗ npm test

> camelcase@7.0.1 test
> xo && ava && tsd

> TypeError: Cannot read properties of undefined (reading 'getAllComments')
> Occurred while linting /Users/leomav/camelcase/index.js:1
> Rule: "unicorn/expiring-todo-comments"
>    at Object.Program (/Users/leomav/camelcase/node_modules/eslint/lib/rules/no-warning-comments.js:193:45)
>    at Program (/Users/leomav/camelcase/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:511:10)
>    at /Users/leomav/camelcase/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:39:18
>    at ruleErrorHandler (/Users/leomav/camelcase/node_modules/eslint/lib/linter/linter.js:1050:28)
>    at /Users/leomav/camelcase/node_modules/eslint/lib/linter/safe-emitter.js:45:58
>    at Array.forEach (<anonymous>)
>    at Object.emit (/Users/leomav/camelcase/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
>    at NodeEventGenerator.applySelector (/Users/leomav/camelcase/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
>    at NodeEventGenerator.applySelectors (/Users/leomav/camelcase/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
>    at NodeEventGenerator.enterNode (/Users/leomav/camelcase/node_modules/eslint/lib/linter/node-event-generator.js:340:14)`

There was an issue in xojs/xo library that was fixed lately https://github.com/eslint/eslint/issues/17167#issuecomment-1539088097
Updating the xo dep to the latest version of this library (currently tried out the v0.54.2) fixes the issue and tests can be ran

**Comment by skavigitp** [comment]
Ran into the same issue. Can confirm that updating the xo dependency to v0.54.2 fixed the issue.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/camelcase/commit/803532b8cbaf0a386a7843f97c1574fc376674c2
