### ISSUE TITLE
x.trim is not a function (camelcase cannot be used with shorthand)

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/camelcase#28]
To reproduce:

```js
// save as `test.js`
const camelCase = require('camelcase');
const keys = [ 'foo', 'bar', 'baz'];
console.log(keys.map(camelCase));
```

```sh
node test
```

```log
λ ~/Public/mongoose-omit-common-fields/ master* node test
arguments { '0': 'foo', '1': 0, '2': [ 'foo', 'bar', 'baz' ] }
/Users/niftylettuce/Public/test/node_modules/camelcase/index.js:41
      .map(x => x.trim())
                  ^

TypeError: x.trim is not a function
    at Array.from.map.x (/Users/niftylettuce/Public/test/node_modules/camelcase/index.js:41:19)
    at Array.map (<anonymous>)
    at module.exports (/Users/niftylettuce/Public/test/node_modules/camelcase/index.js:41:8)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/niftylettuce/Public/test/test.js:4:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by sindresorhus** [comment]
This is exactly why you should never pass a method you don't control directly to iteration callbacks.

`camelcase` accepts multiple arguments, and `.map` provides the element, index, and array, of which it throws on the index, as it's a number.

More info: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-fn-reference-in-iterator.md

**Comment by niftylettuce** [comment]
True, albeit I love the convenience haha.  Thank you!
