### ISSUE TITLE
invalid expression error

### ISSUE THREAD

**Issue by davvit** [sindresorhus/camelcase#67]
I am getting the following error with latest version:
 "camelcase": "^6.0.0",

this is my usage
`  const functionName = camelCase(file.slice(0, -5).split("/").join("_")); `

```
Detailed stack trace: SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid escape
    at preserveCamelCase (/srv/node_modules/camelcase/index.js:11:3)
    at camelCase (/srv/node_modules/camelcase/index.js:63:11)
    at Object.<anonymous> (/srv/index.js:24:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by sschuberth** [comment]
I'm running into a similar issue. What was your solution @davvit?

**Comment by Qix-** [comment]
In the future when making bug tickets, please specify the environment *and version* within which you're using the library.

Node.js:

- If you are using Node.js < 8.3.0, upgrade to at least 8.3.0 (preferably, at least 10.0.0)
- If you are using Node.js >= 8.3.0 < 10.0.0, pass the `--harmony` flag to your `node` process.
- This should be working on Node >= 10.0.0

Browser:
- Does not work in any version of IE (note that Edge is _not_ IE)
- To view browser support, look for your target browser's version support for "Unicode Escapes" on the [MDN Regular Expression compatibility page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility)
